server:
    port: 1472
spring:
    application:
        #应用名称
        name: framework
    datasource:
        url: jdbc:mysql://47.95.242.201:3306/LearnJDBC?useSSL=false?Unicode=true&characterEncoding=UTF-8
        username: learning72
        password: '!Learning72'

#mybatis配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.gc.*.model    
    
#系统信息配置
info:
  app:
    name: "@project.name@"
    description: "@project.description@"  
    version: "@project.version@"  
    spring-boot-version: "@project.parent.version@"    
        
#swagger-ui页面访问密码
security:
  user:
    name: gc
    password: gc123
  basic:
    path:
      - /swagger-ui.html